Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/ccs-oj5MS1KF-py3.9/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/ccs-oj5MS1KF-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/ccs-oj5MS1KF-py3.9/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/.cache/pypoetry/virtualenvs/ccs-oj5MS1KF-py3.9/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/runner/.cache/pypoetry/virtualenvs/ccs-oj5MS1KF-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/ccs-oj5MS1KF-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/ccs-oj5MS1KF-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#DEFINE INPUT

input={
    "General": {
        "interface": "CCS"
    },
    "Twobody": {
                "Xx-Xx": {
                        "Rcut": 6.0,
                        "Resolution": 0.05,
                        "Swtype": "rep"
                }
        }
}
#SAVE TO FILE
with open('input.json', 'w') as f:
    json.dump(input, f, indent=8)
    
#RUN FIT
ccs_fit("input.json")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mIndexError[0m                                Traceback (most recent call last)
Cell [0;32mIn [4], line 20[0m
[1;32m     17[0m     json[38;5;241m.[39mdump([38;5;28minput[39m, f, indent[38;5;241m=[39m[38;5;241m8[39m)
[1;32m     19[0m [38;5;66;03m#RUN FIT[39;00m
[0;32m---> 20[0m [43mccs_fit[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43minput.json[39;49m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m~/work/CCS/CCS/src/ccs/fitting/main.py:361[0m, in [0;36mtwp_fit[0;34m(filename)[0m
[1;32m    349[0m nn [38;5;241m=[39m Objective(
[1;32m    350[0m     atom_pairs,
[1;32m    351[0m     atom_onebodies,
[0;32m   (...)[0m
[1;32m    357[0m     ewald_forces[38;5;241m=[39mewald_forces,
[1;32m    358[0m )
[1;32m    360[0m [38;5;66;03m# Solve QP problem[39;00m
[0;32m--> 361[0m predicted_energies, mse, xx_unfolded [38;5;241m=[39m [43mnn[49m[38;5;241;43m.[39;49m[43msolution[49m[43m([49m[43m)[49m

File [0;32m~/work/CCS/CCS/src/ccs/fitting/objective.py:172[0m, in [0;36mObjective.solution[0;34m(self)[0m
[1;32m    170[0m     [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mDEBUG: Current pair [39m[38;5;132;01m{[39;00m[38;5;28mself[39m[38;5;241m.[39ml_twb[ii][38;5;241m.[39mname[38;5;132;01m}[39;00m[38;5;124m has [39m[38;5;132;01m{[39;00m([38;5;28mself[39m[38;5;241m.[39ml_twb[ii][38;5;241m.[39mN)[38;5;132;01m}[39;00m[38;5;124m knots and [39m[38;5;132;01m{[39;00m([38;5;28mself[39m[38;5;241m.[39ml_twb[ii][38;5;241m.[39mA)[38;5;132;01m}[39;00m[38;5;124m coefficients.[39m[38;5;124m"[39m)
[1;32m    171[0m     [38;5;28mself[39m[38;5;241m.[39ml_twb[ii][38;5;241m.[39mget_spline_coeffs()
[0;32m--> 172[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43ml_twb[49m[43m[[49m[43mii[49m[43m][49m[38;5;241;43m.[39;49m[43mget_expcoeffs[49m[43m([49m[43m)[49m
[1;32m    173[0m     x_unfolded [38;5;241m=[39m np[38;5;241m.[39mhstack(
[1;32m    174[0m         (x_unfolded, np[38;5;241m.[39marray([38;5;28mself[39m[38;5;241m.[39ml_twb[ii][38;5;241m.[39mcurvatures)[38;5;241m.[39mflatten())
[1;32m    175[0m     )
[1;32m    176[0m [38;5;28;01mfor[39;00m onb [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39ml_one:

File [0;32m~/work/CCS/CCS/src/ccs/fitting/spline_functions.py:344[0m, in [0;36mTwobody.get_expcoeffs[0;34m(self)[0m
[1;32m    321[0m [38;5;124;03m"""Calculates coefficients of exponential function.[39;00m
[1;32m    322[0m 
[1;32m    323[0m [38;5;124;03mArgs:[39;00m
[0;32m   (...)[0m
[1;32m    335[0m 
[1;32m    336[0m [38;5;124;03m"""[39;00m
[1;32m    337[0m [38;5;66;03m# NOTE WE SHOULD NOTE INCLUDE INNERMOST POINT WHICH IS IL-DEFINED![39;00m
[1;32m    338[0m [38;5;66;03m# OLD CODE[39;00m
[1;32m    339[0m [38;5;66;03m# aa = self.splcoeffs[0, 0][39;00m
[0;32m   (...)[0m
[1;32m    342[0m [38;5;66;03m# r0 = self.rn[0][39;00m
[1;32m    343[0m [38;5;66;03m# NEW CODE[39;00m
[0;32m--> 344[0m aa [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43msplcoeffs[49m[43m[[49m[38;5;241;43m1[39;49m[43m,[49m[43m [49m[38;5;241;43m0[39;49m[43m][49m
[1;32m    345[0m bb [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39msplcoeffs[[38;5;241m1[39m, [38;5;241m1[39m]
[1;32m    346[0m cc [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39msplcoeffs[[38;5;241m1[39m, [38;5;241m2[39m]

[0;31mIndexError[0m: index 1 is out of bounds for axis 0 with size 1
IndexError: index 1 is out of bounds for axis 0 with size 1

